version: 2
registries:
  github-packages:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.DEPENDABOT_PACKAGES_TOKEN}}
updates:
  - package-ecosystem: npm
    directory: /
    registries:
      - github-packages
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      internal:
        patterns:
          - '@mts241alikhlash/*'
      minor-and-patch:
        update-types:
          - minor
          - patch
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
    groups:
      base-images:
        patterns:
          - '*'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - '*'
