export type ReferenceListKey =
  | 'academicYears'
  | 'semesters'
  | 'classrooms'
  | 'subjects'
  | 'grades'
  | 'teachers'
  | 'positions'
  | 'positionCategories'
  | 'employmentTypes'
  | 'religions'
  | 'bloodTypes'
  | 'occupations'
  | 'educationLevels'
  | 'employees'
  | 'students'
  | 'calendarTypes'
  | 'inventoryMetadata'
  | 'admissionWaves'
  | 'portalCategories'
  | 'portalPublicCategories'

export type ReferenceListStatus = 'idle' | 'loading' | 'ready' | 'failed'
